name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install ruff
      run: pip install ruff
    - name: Check style
      run: ruff check --config .ruff.toml pyscf
    - name: Check NumPy
      run: ruff check --select NPY --ignore NPY002 pyscf
